### ISSUE TITLE
Move to next

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry.rocks#24]
I was thinking this day to move away from Gatsby, I love the idea of statically building the site, but as we will introduce the following features:

- Versioning docs #8 
- Support for translations 

the build would take a lot of time, unless we start caching thigns heavily, but even now the generation of the site seem to take a bit of time. As we have docs previews from the main repo, maybe switching from to a SSR approach might be better :)

**Comment by jkimbo** [comment]
👍 to this. I'm a big fan of Next and I think it could work really well for docs.

There is also https://docusaurus.io/ which might be worth considering as well.

**Comment by jkimbo** [comment]
Also happy to take the lead on this if it helps @patrick91 ?

**Comment by patrick91** [comment]
@jkimbo sure! Feel free to take this one if you have time ☺️
