### ISSUE TITLE
Inline code word break issue for mobile devices

### ISSUE THREAD

**Issue by MattExact** [strawberry-graphql/strawberry.rocks#353]
I have only noticed this on the pydantic page https://strawberry.rocks/docs/integrations/pydantic
It is probably the only page where the inline code is one string that is long enough
It looks especially bad in dark mode

![image](https://user-images.githubusercontent.com/70145864/151442540-6d076655-e61c-4d08-89ac-fd54c7c1149e.png)
![image](https://user-images.githubusercontent.com/70145864/151442505-5f23f1b1-6db1-4d14-ae8a-6ad1a14b308b.png)

Proposed solution:
I think a `break-words` [in the inline code class here](https://github.com/strawberry-graphql/strawberry.rocks/blob/5d708e4202db25fa6164247bde16273b2b8e64a2/components/mdx.tsx#L178-L180) should fix it but wanted to check in before doing the PR in case anyone has a better idea
There probably are other ways like `text-ellipsis` or `text-clip` but I would say we want to display the whole string

![image](https://user-images.githubusercontent.com/70145864/151443820-6ac4ac76-e51a-46ae-85be-f6327843df9c.png)

**Comment by patrick91** [comment]
> There probably are other ways like text-ellipsis or text-clip but I would say we want to display the whole string

yes, I agree :) Break works sounds like the way to go 😊
